### ISSUE TITLE
unable to use --aggregate after use --4d

### ISSUE THREAD

**Issue by conniecl** [CshlSiepelLab/phast#10]
Hi,
I used the phast for 4d sites extract in different chromosome, and want to use --aggregate to combine the chromosome result, but failed:
```
WARNING: use --unordered-ss unless you're sure you need order
ERROR: msa_concat_from_files requires an ordered alignment.
```
Here is my command:
```
for i in {1..10};
do
msa_view chr${i}_3.sort.maf --in-format MAF --4d --features Zea_mays.chr$i.T01_cds.gtf >chr${i}_3.4d-codons.ss
msa_view chr${i}_3.4d-codons.ss --in-format SS --out-format SS --tuple-size 1 >chr${i}_3.4d-sites.ss
done
msa_view --aggregate maize,sorgum,millot chr1_3.4d-sites.ss chr2_3.4d-sites.ss chr3_3.4d-sites.ss chr4_3.4d-sites.ss chr5_3.4d-sites.ss chr6_3.4d-sites.ss chr7_3.4d-sites.ss chr8_3.4d-sites.ss chr9_3.4d-sites.ss chr10_3.4d-sites.ss >all.sites.ss
```
After reading the msa_view -h file, I found using `--4d` will apply `--unordered-stats` command at same time? May be is the reason that --aggregate failed? But how to change it?
How can I merge the site information between difference chromosome? Hope can get some advice, and thanks in advance.

**Comment by Ninet93** [comment]
Hello,

Did you find how to fix this problem, @conniecl ? I'm currently facing the same problem using **msa_view -aggregate** after retrieving 4d_sites.ss for several scaffolds (equivalent to chromosomes in my case). 

Thank you in advance,

Best regards.

**Comment by siepellab** [comment]
Hello, 
I would suggest using --unordered-ss here. In the above example, something like

msa_view --unordered-ss --aggregate maize,sorgum,millot chr1_3.4d-sites.ss chr2_3.4d-sites.ss chr3_3.4d-sites.ss chr4_3.4d-sites.ss chr5_3.4d-sites.ss chr6_3.4d-sites.ss chr7_3.4d-sites.ss chr8_3.4d-sites.ss chr9_3.4d-sites.ss chr10_3.4d-sites.ss >all.sites.ss

If that doesn't work make sure that the alignment files are split by chromosome and sorted by the coordinate of the reference genome.
Also make sure that the corresponding gff features file is from the reference species and has the same chromosome only. 

Hope this helps!
Ritika

**Comment by Ninet93** [comment]
Hello, 

Thanks for replying so fast.
I tried as you mentioned, but still, it doesn't work.

In the alignment files, the reference is called 'Species.ContigX'. In the annotation files, the reference is called 'Species'. Is it correct or should it be 'ContigX' in the annotation files ? 

In addition, should I have all .maf, all .ss and all .gff3 files in the same folder (msa_view 'sub-commands' need them indirectly?) ?


Many thanks,

Best regards

**Comment by siepellab** [comment]
Hello, 

The reference name should match exactly in the alignment and annotation files. The location of the files doesn't matter as long as you use the full path of the file. 

Hope this helps!
Ritika

**Comment by Ninet93** [comment]
Hi again,

The problem could be that each chromosome has its own 'coordinates' meaning that the coordinates of Chr0 and Chr1 start both at 0 ? I really can't figure out why it doesn't work... 

Sorry again for the inconvenience,

Many thanks,

Best regards

**Comment by siepellab** [comment]
Hello,

Please make sure that the alignment files are split by chromosome and sorted by the coordinate of the reference genome. 
Also make sure that the corresponding gff features file is from the reference species and has the same chromosome only.

If that still doesn't solve the issue, please send us sample files so that I can replicate the error on my end. 

Thanks!
Ritika

**Comment by helloworldABCD1234** [comment]
Hello-- Does the species in the aggregate refer to all species in the maf? Some mafs do not include all species, such as the whole maf, which generates many sub mafs by chromosome segmentation. Among these sub mafs, there are some that do not include all species. If the whole maf has 15 species (whole genome alignment), then PhastCons can use this model to analyze only 9, 10, 11, 12, and 13 species' maf files, isn't it accurate?
