### ISSUE TITLE
Homepage is advertising version 1.5 but it is at least not tagged here

### ISSUE THREAD

**Issue by tillea** [CshlSiepelLab/phast#13]
Hi,
for the Debian packaging it would help a lot if you would tag releases in Github.  That way we get automatic notification about new releases and will try to follow quickly.  BTW, if you want to be really sure that Debian follows your release cycle in time a short notice to debian-med@lists.debian.org is fine.
Kind regards, Andreas.

**Comment by siepellab** [comment]
Hello, 
I will tag the releases in Github and make sure to send an email every time we have a new release.

Sorry about that.

Ritika

**Comment by tillea** [comment]
On Thu, Oct 18, 2018 at 10:36:50AM -0700, siepellab wrote:
> I will tag the releases in Github and make sure to send an email every time we have a new release.
Thanks a lot.  Version 1.5 just uploaded to Debian mirror.
