### ISSUE TITLE
issues on architectures where char is unsigned

### ISSUE THREAD

**Issue by tillea** [CshlSiepelLab/phast#15]
Hi,
there ia a Debian [bug report](https://bugs.debian.org/911983) about build failures on architectures where char is unsigned.  The code actually builds but when running the test suite

    *** Testing msa_view ***
    msa_view hmrc.ss -i SS --end 10000 > hmrc.fa

the command will not end and is finally killed with signal TERM after 150 minutes of inactivity.  Do you see any way to track this down?
Kind regards, Andreas.

**Comment by AdrianBunk** [comment]
This is a bug pattern that seems to be in many places in phast:
 ```
char c;
...
while ((c = (char)getopt_long(argc, argv, "i:o:s:e:l:G:r:T:a:g:c:C:L:I:A:M:O:w:N:Y:X:fuDVxPzRSk4mh", long_opts, &opt_idx)) != -1) {

```
The casts in commit 273b8ce6 silenced the warnings where the compiler was warning about this bug...

**Comment by tillea** [comment]
Is there any intend to fix this bug?  I'm just asking because if this bug persists phast will probably be removed from Debian.  Kind regards, Andreas.

**Comment by siepellab** [comment]
Hello,
Sorry for missing this issue. 
We are working on it and will submit a fix soon. 

Thanks!
Ritika

**Comment by tillea** [comment]
Thank you for your response.  Technically I would prefer if that bug would remain open and would be closed once a patch is available.  The bug closal has triggered a mechanism in Debian bug tracking system that there is a solution (which is not the case) and I might miss the point in time once a real solution is available.
Kind regards and thanks for caring for this anyway, Andreas.

**Comment by tillea** [comment]
On Tue, May 12, 2020 at 06:24:29AM -0700, siepellab wrote:
> Reopened #15.
Thanks a lot, Andreas.
