### ISSUE TITLE
option to over-ride same srcName error?

### ISSUE THREAD

**Issue by sorrywm** [CshlSiepelLab/phast#18]
I am trying to use maf_parse to split a maf generated from a [hal](https://github.com/ComparativeGenomicsToolkit/hal), which has some blocks where the same source sequence is included multiple times. Is there any way to over-ride the check in maf_block for unique names? I'd be happy to get an output file with multiple sequences with the same name. Here is the relevant error:
ERROR: mafBlock has two alignments with same srcName (repeated_sequence_name)

**Comment by ekopania** [comment]
Hi, I just ran into the same issue! Was this ever addressed?

**Comment by gwct** [comment]
I also am interested in whether this is possible.

**Comment by stephenturner** [comment]
Same 👍

**Comment by stephenturner** [comment]
Relevant part of the code. I'm wondering what would happen here if one were to comment this out. 

https://github.com/CshlSiepelLab/phast/blob/b6088c766b9f483bdf58708278cf1560b4930721/src/lib/msa/phast_maf_block.c#L292-L294

**Comment by pkathail** [comment]
I'm also running into this issue. Did any of you end up finding a workaround?

**Comment by ekopania** [comment]
I found [this tool](https://github.com/ComparativeGenomicsToolkit/mafTools/tree/master/mafDuplicateFilter) to filter duplicates from MAF files. It keeps the duplicate sequence that best matches the consensus of the MAF block. I'm running maf_parse on the output and it seems to be working, so if you do not need to keep all duplicate sequences, this could be a work around.
