### ISSUE TITLE
ERROR: LAPACK required for matrix diagonalization.

### ISSUE THREAD

**Issue by AIBio** [CshlSiepelLab/phast#20]
Hi~
I want to use the function "phyloFit" to fit mod for my maf file, but my computer return an error.

`
$ phyloFit --tree "((hg38,panTro4),(mm10,rn6))" --subst-mod HKY85 --out-root chr12_filter chr12_filter.maf

$ Reading alignment from chr12_filter.maf ...
Compacting sufficient statistics ...
Fitting tree model to chr12_filter.maf using HKY85 ...
numpar = 6
**ERROR: LAPACK required for matrix diagonalization.**
`
I have noticed the NOTEs you writed on the README.txt.
> Part 1 - Installing Clapack - (If you already have Clapack installed, skip to Part 2)
    1. Download Clapack from the following URL http://www.netlib.org/clapack/clapack.tgz
    2. Unzip clapack.tgz with the command 'tar -xvzf clapack.tgz'
    3. Go into the newly created Clapack directory (i.e. 'cd CLAPACK-3.2.1') 
	and type 'cp make.inc.example make.inc && make f2clib && make blaslib && make lib'
       Note: Building Clapack can take several minutes depending on your system
 
> Part 2 - Installing Phast
    4. Download a copy of Phast from http://compgen.cshl.edu/phast/ 
	and extract the contents of phast*.tgz using 'tar -xvzf phast*.tgz'
    5. Change directory to 'phast/src/' and run 'make CLAPACKPATH=/usr/local/software/clapack'
	replacing '/usr/local/software/clapack' with the path of your
	Clapack install (e.g., CLAPACKPATH=/home/username/CLAPACK-3.2.1)
    6. The Phast binaries should be created in the '../bin/' directory

> **It's possible to compile the software without LAPACK by commenting out both the VECLIB and CLAPACKPATH lines in src/make-include.mk.  In this case, some programs will be usable, but programs that require matrix diagonalization will abort at the critical point of calling a LAPACK routine.**

Here, I want to kown the more specific installing pipeline (the relationship or dependency between PHAST, clapack and lapack, and the order when I install them) in order to successfully use all tools in PHAST packags. I don't have solid computer science knowledge. So, if you can tell me the answer, I will appreciate it.

Before submitting this issue, I tried to figure this problem out. I re-installed the Clapack and PHAST. And them, ran the same scripts and got the same error. 

But, when I run:

`
$ yum install lapack
$ Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
 * base: centos.ustc.edu.cn
 * epel: mirrors.aliyun.com
 * extras: centos.ustc.edu.cn
 * updates: centos.ustc.edu.cn
(1/5): pgdg11/7/x86_64/primary_db                                                                                                                                  | 336 kB  00:00:17     
(2/5): pgdg94/7/x86_64/primary_db                                                                                                                                  | 362 kB  00:00:20     
(3/5): pgdg10/7/x86_64/primary_db                                                                                                                                  | 384 kB  00:00:21     
(4/5): pgdg96/7/x86_64/primary_db                                                                                                                                  | 392 kB  00:00:30     
(5/5): pgdg95/7/x86_64/primary_db                                                                                                                                  | 380 kB  00:00:45     
Package lapack-3.4.2-8.el7.x86_64 already installed and latest version
Nothing to do
`
It seem like the lapack is already installed on my computer.

So, could you help me address this problem ??? (PS: I tried to intall lapack, but failed...)

**Comment by siepellab** [comment]
Hello,
CLAPACK is required to be installed before installing the PHAST package. 
It seems you have tried installing lapack using yum install. We need to install CLAPACK for PHAST.
Please try following the exact steps in the README and installing CLAPACK from source. 
Once you do that then please follow part 2 of the README to install the PHAST package. 
If you are still unable to install PHAST after installing CLAPACK from source, please let us know.

Thanks!
Ritika

**Comment by AIBio** [comment]
Thank you for your reply.
I have solved this problem. I tried to complie phast in conda environment in which the lapack is successfully installed. With the help of clapack, I installed the phast and ran the scripts. I got the expected results. I don't know why the base environment in which lapack was installed through yum function canno help phast to complie. But conda worked. I wish my experiences can help another people who could met similar issue.

I have met another problem about phylogenetic tree. I want to plot phylogenetic tree with R package ggtree and treeio, but I don't find relevant tools to output Newick format file. Can phast complete this task? or Could you recommend some tools or learning materials for me ??
Thanks again!
Hanwen

**Comment by siepellab** [comment]
Hello, 
If I understand correctly, you are not sure how to convert the tree from the output (.mod) file to newick format.
The tree in newick format is available in the .mod file. You should be able to parse it out from the file using something simple like sed in bash.

Something like this should work 

sed -n -e 's/^.*TREE: //p' out.mod > tree.newick

Hope this helps!
Thanks!
Ritika
