### ISSUE TITLE
PhyloP; Error: mm_exp_real  t=nan

### ISSUE THREAD

**Issue by sergioSEa** [CshlSiepelLab/phast#21]
Hello,

I am trying to use phyloP to estimate acceleration and conservation pvalues across a MSA of one mitochondrial gene of 352 bp. 
I have two different MSAs of the same gene, one that includes 436 different species and a second one including 696. I am running my analysis in a MacOS Mojave (10.14.6), where I successfully downloaded and compiled Phast v1.4.

I have used phyloFit to create a mod file under REV model. This works with no problem in any of the alignments. Then I used the following command  to run phyloP

 >/PATH/to/phyloP --base-by-base  --method LRT --mode CONACC $MOD $FASTA > report.fa 

It works just fine with my alignment of 436 organisms, nevertheless, when I run it in the 696 organisms one I get the following error:

> ERROR mm_exp_real: got P->size=4, Q->sizse=4, t=nan

The error seems to come from the script markov_matrix.c, but I cannot figure out what is causing the parameter t to be nan. 

I have also checked the outcome using different methods:
SCORE
>ERROR incomplete_gamma got x=nan, a=0.500000, type=q

GERP
>ERROR mm_exp_real: got P->size=4, Q->sizse=4, t=nan

SPH
>Segmentation fault: 11

Surprisingly, I have been able to run it with phastCons without problem:
>phastCons $MSA --estimate-trees $TREE $MOD

I have been checking for possible problems in the sequence or tree but I cannot figure out anything weird. 

I am looking forward for your answer! Thank you in advance.

**Comment by siepellab** [comment]
Hello, 
Would you be able to send me the files or a small subset so that I can try to replicate the error on my end and take a closer look.

Thanks!
Ritika

**Comment by sergioSEa** [comment]
Hi Ritika,

I have sent you the dataset at your cshl.edu mail.

Thank you for looking into it!

**Comment by ekopania** [comment]
Hi, I am running into a similar issue using rphast v1.6.11. Did this issue get resolved, and what was the solution? Thank you!

**Comment by andrewSharo** [comment]
Hi Ritika,
I am experiencing the same issue that Sergio mentioned here. Can you describe how this was resolved? 
Best, Andrew

**Comment by helloworldABCD1234** [comment]
phyloP --branch
Can we directly fill in the leaves as the species of the tree evolution terminal, or can we only fill in the nodes？
Is filling in leaf nodes a way to calculate the conservation of leaf node species in the overall population？
﻿
