### ISSUE TITLE
run phastcons  with warnings

### ISSUE THREAD

**Issue by yuzhenpeng** [CshlSiepelLab/phast#22]
Hi, Dear phast developer.

When I used the Phastcons met with the warnings. 
My command is that : `phastCons --estimate-rho window.ss --no-post-probs window.ss nonconserved-4d.mod`
Although runs pretty well, it also showed some warnings:
like that `WARNING: likelihood decresed during EM .....` .
![image](https://user-images.githubusercontent.com/31943277/69927976-18923700-14f5-11ea-8a54-ba2546b57938.png)

Could you please give me some help.
Thank you.

**Comment by siepellab** [comment]
Hello, 
The difference in the likelihood is pretty small so in this case I wouldn't worry about it.

Hope this helps!
Ritika

**Comment by yuzhenpeng** [comment]
Hi,Ritika 
Thanks for your kind help.
In addtion, when used the msa_view to extract 4d sites, I met another question.
command: `msa_view --in-format MAF Superscaffold1.maf --4d --features chr1.gff > 4d-codons.ss`

GFF file format:
![image](https://user-images.githubusercontent.com/31943277/70109169-0c89af00-1686-11ea-8305-70b2c9edbf73.png)
MAF file:
![image](https://user-images.githubusercontent.com/31943277/70109215-29be7d80-1686-11ea-90e7-0791d13966bf.png)

But, I got the warnings: ERROR name Superscaffold1 not present in MSA

**Comment by siepellab** [comment]
Hello, 
You need the species name in the gtf file. So it should be plar.Superscaffold1 instead of just Superscaffold1 in the first column of the gtf.
Also keep in mind that your gtf files should be split by chromosomes.

Hope this helps!
Ritika

**Comment by yuzhenpeng** [comment]
It works.
Thank you very much, Ritika.

**Comment by yuzhenpeng** [comment]
Dear Ritika.
I am sorry for disturbing again.
I want to know how to set the parameter`--target-coverage xx --expected-length xx`.
Do these parameters have certain limitations? Like a maximum or a minimum? 
In fact, when I use `--target-coverage 0.6 --expected-length 45` will get more conserved elements.is this correct?
