### ISSUE TITLE
Combined CNEE located in two blocks

### ISSUE THREAD

**Issue by Ran-tian** [CshlSiepelLab/phast#23]
Dear author,
I want to extract the cnee from maf based on the bed, but I found some CNEE span two blocks. How can I combined these blocks for this CNEE to obtain a intact CNEE block. 
Looking forward to your reply.
Thanks.

**Comment by siepellab** [comment]
Hello, 
How are you extracting the CNEEs? If you use msa_view - http://compgen.cshl.edu/phast/help-pages/msa_view.txt, it should produce what you are asking for. The way PHAST tools work is that they project the alignment on the reference genome, then when a tool like phastCons is run, it calls conserved elements without any knowledge of the MAF blocks which is how you get elements that split across blocks. 
Hope this helps!
Ritika
