### ISSUE TITLE
Input MAF where multiple scaffolds of one species overlap in one region

### ISSUE THREAD

**Issue by Shunsuke-Kanamori** [CshlSiepelLab/phast#24]
Dear PHAST developer,

We input MAF where multiple sequences of one species overlap in one region to PHAST, but the software seemed to work normally.
Does the software select any one sequence in such case?

Please help me to understand.

Thank you in advance.

**Comment by ramaniritika** [comment]
Hello, 
Do you mean that there is overlap in the annotations in the features files? 
Also which PHAST tool are you using? 

Thanks!
Ritika

**Comment by Shunsuke-Kanamori** [comment]
Hello, Ritika
Thanks for your quick reply.
I'm using PhastCons.
I mean that MAF file shows the following situation:
```
species_A_fragment_1 ATGCATGCATGCATGCATGCATGC
species_B_fragment_1 ATGCATGCATGCATGCA-------
species_B_fragment_2 ----ATCCATACATGCATGCATGC
species_C_fragment_1 ATGCATGCAGGCGGGCATGCATGC
```
In this example, fragment 1 and 2 of species B overlap in the same region.
In this case, is one of the fragments selected? Or will such regions be removed?

Thanks
Shunsuke

**Comment by ramaniritika** [comment]
Hi Shunsuke,

I'm pretty sure that the last fragment in the block will be selected. If you wanted to be sure, you could create a short MAF with the overlapping region and use msa_view to read it in andvoutput it in FASTA format, and see which fragment is retained. Sorry this is not the best solution but should give you an idea on how PHAST will handle it.

Hope this helps, 
Ritika

**Comment by Shunsuke-Kanamori** [comment]
Hi Ritika,

Thanks for your detailed answer very much :-)
I will try to use msa_view and check the result.
And maybe I should pre-select a long or best alignment using single_cov2 or something.

Thank you again,
Shunsuke

**Comment by ramaniritika** [comment]
Hi Shunsuke,
Yes pre-selecting the best alignment would work too.

Ritika
