### ISSUE TITLE
Unexpected long conserved regions

### ISSUE THREAD

**Issue by fukusakamoto** [CshlSiepelLab/phast#25]
Hello,
I am trying to use phastCons to estimate conserved regions using whole-genome alignments, and I would like to use the results for calculating p-values in phyloP.

I would like to make less than 100 bp conserved regions, so I used the following parameters to phastCons:
expected_length=20, target_coverage=0.3, but most of the results were more than 1000 bp.

I changed the parameters and reanalyzed my data a few times, but the tendency was the same. What do you think could be the cause of this problem?

I read the phyloP paper (Pollard _et al._ 2010), and I thought that phyloP targets regions less than 100 bp to calculate p-values. Would it be a problem to use regions over 1000 bp for phyloP? Should I make the length of the input data uniformly?

Thank you very much in advance.

**Comment by ramaniritika** [comment]
Hello, 
The expected_length parameter is just a prior for phastCons. The data drives the actual inference itself, so if you get more than 1000 bp each time that probably means that the conserved regions are genuinely that long. I don't think this should be an issue. 

Thanks!
Ritika

**Comment by fukusakamoto** [comment]
Thank you very much for your prompt reply! 
I have one more question. In phyloP, the p-values of computation actually reflect the length of the input data? 
In that case, when I compare a long with a short region which have the same p-values, I think the degree of conservation or acceleration per one site is different.
I would like to see the degree of conservation or acceleration on the same scale, so I am thinking whether I should correct p-values by length, but I don't know how to do that.

**Comment by ramaniritika** [comment]
Hello, 
By default, p-values are produced for the entire input alignments. But you can define intervals within an alignment in a features file (bed or gff) to output a table of p-values and related statistics with one row per feature.
This can be done with the --features option. 
http://compgen.cshl.edu/phast/phyloP-tutorial.php#tuts

Hope this helps!
Ritika
