### ISSUE TITLE
Tree specification error

### ISSUE THREAD

**Issue by CraigJAnderson** [CshlSiepelLab/phast#26]
Hi,

I'm trying to use Phylofit in the following way:

phyloFit --tree "(loxAfr3,(((canFam3,felCat8)DOG-CAT(oviAri3,bosTau8)SHEEP-COW),(rheMac3,(oryCun2,(jacJac1,(micOch1,(Rattus,(CAROLI_EiJ,(CAST_EiJ,(C57B6J,C3H_HeJ)MM10)))))))))" --msa-format MAF --out-root testout tmp2.maf

However, I achieve an error that I don't understand given the range of examples in the phyloFit tutorial: ERROR (tree parser): invalid binary tree (too many children)

My goal is to derive nucleotide resolution conservation scores for my favourite regulatory regions across 4 murine genomes using GERP++. To get a neutral tree for a simple placental mammal phylogeny, I'm pulling 4D sites conserved across the tree using hal and although there is Phast capability now implemented in hal, it's clearly still in development.

An example variant from my MAF is below. I'd appreciate any suggestions you can offer.

All the best,

Craig

#maf version=1 scoring=N/A
# hal ((((((((((((CAST_EiJ:0.001,(((((C57B6J:1e-06)Anc23:1e-06)Anc21:1e-06,(((((C3H_HeJ:1e-06)Anc29:1e-06)Anc28:1e-06)Anc26:1e-06)Anc25:1e-06)Anc22:1e-06)Anc19:1e-06)Anc18:1e-06)Anc17:0.0001)Anc16:1e-06)splitPoint:1e-06)Anc14:0.015,CAROLI_EiJ:0.02)Anc13:0.01)Anc12:0.02,Rattus:0.013)msca_root:0.065,micOch1:0.15)stitch1:0.117,jacJac1:0.1859)stitch2:0.07,oryCun2:0.21)stitch3:0.01,(rheMac3:0.007)primates:0.1)stitch4:0.02,((oviAri3:0.019,bosTau8:0.0506)oviBos:0.17,(canFam3:0.11,felCat8:0.08)stitch5:0.06)stitch6:0.02)stitch7:0.02,loxAfr3:0.15)stitch8;

a
s       C57B6J  112640438       1       +       171031299       T
s       CAST_EiJ        93734134        1       +       147371385       T
s       CAROLI_EiJ      105932501       1       +       158037523       T
s       Rattus  32341851        1       +       177180328       T
s       micOch1 5173957 1       -       8569453 T
s       jacJac1 3789592 1       +       5915255 T
s       oryCun2 76171777        1       +       111700775       T
s       loxAfr3 28739460        1       -       42373024        T
s       oviAri3 73107280        1       +       135437088       T
s       bosTau8 73856928        1       -       148823899       T
s       canFam3 66235175        1       +       123869142       T
s       felCat8 70363084        1       +       127282370       T
s       rheMac3 84692788        1       +       155416530       T
s       C3H_HeJ 109823276       1       +       168548779       T

**Comment by ramaniritika** [comment]
Hello, 
PHAST requires the tree to be binary. The DOG-CAT and SHEEP-COW in the tree were causing the issue. Try it with this tree and it should work.

(loxAfr3,(((canFam3,felCat8),(oviAri3,bosTau8)),(rheMac3,(oryCun2,(jacJac1,(micOch1,(Rattus,(CAROLI_EiJ,(CAST_EiJ,(C57B6J,C3H_HeJ))))))))));

Hope this helps!
Ritika

**Comment by CraigJAnderson** [comment]
That worked a treat, thanks!
