### ISSUE TITLE
header rename is a painful

### ISSUE THREAD

**Issue by diekhans** [CshlSiepelLab/phast#30]
The header rename for:
  "future proof header names by adding 'phast_' to the beginning and the"

is proving very painful for HAL, with users attempting to compile against various versions of PHAST.

It would be far easier to work around if the namespace was implemented by a directory rather than
a file prefix.  So phast/em.h rather than phast_em.h.

PHAST would #include <phast/em.h>, to prevent it from pick up other files with the same name.

HAL could then use -I to direct to the right location until it is switch.

Also, when a package has a large number of includes, putting them in a directory is a common practice to help keep the size of /usr/include under control

**Comment by ramaniritika** [comment]
Hello, 
This has been addressed in the v1.6 that i just released. Please let me know if it doesn't work!
Ritika
