### ISSUE TITLE
Problems in using maf_parse to get sub-alignment

### ISSUE THREAD

**Issue by biozhangzhou** [CshlSiepelLab/phast#31]
Hello,Sir:
I think i don't really understand what's the help message below means.
"    --catmap, -c <fname>|<string>
        (Optionally use with --by-category) Mapping of feature types to
        category numbers.  Can either give a filename or an "inline"
        description of a simple category map, e.g.,
         --catmap "NCATS = 3 ; CDS 1-3" or
         --catmap "NCATS = 1; UTR 1". 
"
And I want to how to get 4d sites from maf using maf_parse.
Thanks

**Comment by ramaniritika** [comment]
Hello, 
I am not sure how you got this message but you can't extract using maf_parse. But you can use msa_view instead.
If you have a features file describing coding regions, you can do something like this - 

    msa_view data.fa --4d --features genes.gff > 4d-codons.ss  

You can find more details on all the options for msa_view here - http://compgen.cshl.edu/phast/help-pages/msa_view.txt

Hope this helps! 
Ritika

**Comment by biozhangzhou** [comment]
I have followed you suggestion. But it result a SS file with many * and some warning messages; And I don't konw the SS format clearly; where can i find more description about SS file and those scripts ?

**Comment by biozhangzhou** [comment]
I have followed you suggestion. But it result a SS file with many * and some warning messages; And I don't konw the SS format clearly; where can i find more description about SS file and those scripts ?

**Comment by ramaniritika** [comment]
Hello, 
You can find more info on the following pages.
 
http://compgen.cshl.edu/phast/resources.php
http://compgen.cshl.edu/phast/phastCons-HOWTO.html
http://compgen.cshl.edu/phast/help-pages/msa_view.txt


Thanks!
Ritika

**Comment by ramaniritika** [comment]
Also, you can use the --out-format FASTA option to get the output in FASTA format instead of SS.

**Comment by biozhangzhou** [comment]
Thank you for patiention. I may have much more question. I use the cactus out .hal and hal2maf to get maf file. There is a header : 
"
##maf version=1 scoring=N/A
# hal (ZJU-Pek:0.00531962,(((ZW:0.00398503,LC:0.00468975)Anc4:0.00110473,(LW:0.00567776,...）
“
where msa_view will get a wrong  NAMES such as "NAMES = Chr25,LW:0,Anc5:0,Anc2:0,Anc6:0..." which LW:0 , Anc5:0,Anc2:0,Anc6:0 are all wrong. So the body of the SS will be wrong either.
I don't why would it happend.

**Comment by biozhangzhou** [comment]
After I deleted the header, this error seems gone. And cause the maf are multi-alignment, so the NAMEs for one chromosome SS file such Chr25.ss will be more than the genome number(individuals * chr25) due to the apperence of other chromosomes and ancestor chromosomes, here is one more question about this: If other chromosome like chr1 have a little Segment duplication Orhology with chr25, then chr1 will appear in the chr25.ss file but wth a lot of *(None) except for the little SD region. Then we may aggragate chr1.ss and chr25.ss, what will your scripts do to handle it ?

**Comment by biozhangzhou** [comment]
One more question:
when I extract the 4d sites with  --4d the defaults is " Implies --out-format SS --unordered-stats --tuple-size 3 --reverse-groups transcript_id." which results are unordered;
Then, I use the --aggragate to merge different .ss files, it comes:
"WARNING: use --unordered-ss unless you're sure you need order
ERROR: msa_concat_from_files requires an ordered alignment."

**Comment by ramaniritika** [comment]
Hello, 

- PHAST expects the alignments to be in standard formats so any extra header will probably cause an error. 
- All PHAST software including msa_view require only one reference sequence per alignment file- and different
chromosomes of the same organism are considered different sequences, so the MAF file needs to be broken up by refseq chromosome.
- Once you have extracted 4d sites, you can use msa_view --aggregate to combine the 4d sites from several chromosomes.
- You should use the --unordered-ss option here. The "order" that it refers to is the ordered of the alignment columns. Once you have extracted the 4d sites and removed non-4d sites, you have basically lost the coordinate system that keeps track of the order of your sites. So you should be okay using the --unordered-ss option here.

Hope this helps!
Ritika

**Comment by biozhangzhou** [comment]
I think the problems is even when used "--unordered-ss" , error still happens.
 
_**$ ~/1.bin/phast/bin/msa_view --unordered-ss  --aggregate chr24-4d-codon.ss chr25-4d-codon.ss**_
WARNING: use --unordered-ss unless you're sure you need order
ERROR: msa_concat_from_files requires an ordered alignment.

**Comment by ramaniritika** [comment]
Hello, 
Please make sure the reference name matches exactly in the alignment and annotation files.

Ritika
