### ISSUE TITLE
MAF format error when using PhyloP

### ISSUE THREAD

**Issue by SimonaSecomandi** [CshlSiepelLab/phast#33]
Hello,

I extracted a MAF file referenced to my target species from a HAL alignment file (progressive Cactus output) and I'm trying to run PhyloP on it with my neutral model:

`phyloP --method LRT --wig-scores --mode CONACC Hirundo_repeats_neutral_model.mod Hirundo_noAncestors_onlyOrthologs.maf  > PhyloP_scores.wig `

However, I got this error:

warning: maf_read: MAF file must be sorted with respect to reference sequence if store_order=TRUE.  Ignoring out-of-order blocks
ERROR maf_read_subset: invalid idx_offset -2

Do you have any solutions? Many thanks!

**Comment by ramaniritika** [comment]
Hello,
I would suggest checking that the MAF follows the following conventions:
- the first species in each block should be the same throughout the file. This is the "reference genome"
- the MAF is sorted by reference genome coordinate
- the MAF only contains a single chromosome from the reference genome. PhyloP should be run on each chromosome separately.
If that doesn't help, maybe you can reproduce the error in a small MAF file and send it to us and we can take a look.
Ritika

**Comment by SimonaSecomandi** [comment]
Hi,

many thanks for your answer. My MAF contains all the chromosomes, therefore I had to split it into the different chromosomes. With these MAFs, PhyloP ran without problems.

I only have one concern about this approach. Since I'm running phyloP on single chromosomes (MAFs referenced at my species chromosome sequences), has the neutral model to be estimated on each chromosome or it could be done on the entire MAF? I generated a neutral model on a MAF exported on 100.000 random bases within ancestral repeats (ancestral genome of all my species, outputted by cactus), referenced at the ancestral genome.

Many thanks,

Simona

**Comment by ramaniritika** [comment]
Hello - 
You can use the same neutral model for each chromosome. 
Ritika

**Comment by helloworldABCD1234** [comment]
phyloP --branch
Can we directly fill in the leaves as the species of the tree evolution terminal, or can we only fill in the nodes？
Is filling in leaf nodes a way to calculate the conservation of leaf node species in the overall population？
﻿
