### ISSUE TITLE
how to use it!

### ISSUE THREAD

**Issue by Golden-proteogenomics** [CshlSiepelLab/phast#35]
hello,
this a good software for bioinformatic analysis, however, there is an important question for want to use it that is how to use it. there is no clear description in download example files, readme file and  --help. So, could you give some suggestions for users to correctly use it? 
thanks for your attention!
shuai

**Comment by ramaniritika** [comment]
Hello, 

You can find detailed description, examples and other resources here - http://compgen.cshl.edu/phast/
Please go through everything and let us know if you have specific problems/issues.

Thanks!
Ritika

**Comment by Golden-proteogenomics** [comment]
Hello,
Thanks for your reply and give me resources as soon as possible. however, there are two specific questions that cannot find a resolve method. one question is that software without responding file, such as "phyloFit -h" will present the "phyloFit pair.fa" that cannot find in download files so that I cannot know what "pair.fa" used what specific format data to do. if give me a specific command and files, I believe that software will be more applicable.  Another question is even I know that "pair.fa" was aligned sequence in Fasta, but some problem will raise in the other software because no specific file above "xxx -h".  Such as, I use the MGEA to produce an aligned fasta file which named “K530A.60.forwared” and tree files "Newick.Export.nwk" used ML and produce a “phyloFit.mod” file with command “phyloFit ../data/K530A.60.forwared.fas --tree ../data/Newick.Export.nwk”. and then,I use the other software with the command "phyloP phyloFit.mod  ../data/K530A.60.forwared.fas > report.txt" that will produce a nothing report.txt file with “Segmentation fault (core dumped)” error. So those files were added appendix as follows, Could you give me a suggestion.
Sincerely hope to get your reply!
[data.zip](https://github.com/CshlSiepelLab/phast/files/6388549/data.zip)
Shuai

**Comment by ramaniritika** [comment]
Hello, 

I am not sure if you are running the tools correctly. 
Please go through the tutorials for phyloFit - http://compgen.cshl.edu/phast/phyloFit-tutorial.php and phyloP - http://compgen.cshl.edu/phast/phyloP-tutorial.php. 

Thanks!
Ritika
