### ISSUE TITLE
FATAL ERROR: out of memory 

### ISSUE THREAD

**Issue by Nikos22** [CshlSiepelLab/phast#37]
Hello,

When trying to run default phylofit on the command line, on alignments of relatively short sequences, I get the following error :

> Reading alignment from alignments/alignment.fsa.ali ...
> Extracting sufficient statistics ...
> FATAL ERROR: out of memory.

I provided the same exact files to the phastWEB interface and used the "Run Phylofit only" option, and it worked fine, returning a .mod file.

However when trying to use this .mod file to run other phast programs on my command line, such as phyloP or dless, I get the same "out of memory" error.

Any help would be greatly appreciated.

**Comment by ramaniritika** [comment]
Hello, 

It seems like it maybe an error with your computer since the files work on phastWeb. Do you have enough memory free? Can you try it on a different computer to see if you can replicate the error? If you still get the error then please send a small example of the files so that I can try to replicate the error on my end.

Ritika

**Comment by Nikos22** [comment]
Hi Ritika,

Thanks a lot for your reply.
I tried it on my lab's cluster and it actually worked! 
Although I am a bit puzzled by the fact that 7gb of memory weren't enough to run dless, given the mod file, on a small alignment of 20 or so sequences.
Is this supposed to happen?

Nikos

**Comment by ramaniritika** [comment]
Hi Nikos,

The parameter estimation could be computationally expensive and could take a lot of time and memory. 7GB may not be enough for the whole alignment.
You can divide the genome up into chunks of not more than a few MB and run them in parallel which would probably work better.

Hope this helps!
Ritika
