### ISSUE TITLE
Can phyloFit use multi-cpu at the same time?

### ISSUE THREAD

**Issue by Rusfell** [CshlSiepelLab/phast#39]
Hello,

When trying to run phylofit on the command line, it toke 2 days per run. So can an phyloFit use multi-cpu at the same time?

my command:
`phyloFit --tree tree.nh --init-random --subst-mod SSREV --out-root neut4d --msa-format SS --sym-freqs --log phyloFit_neut4d.log neut4d_input.ss &> phyloFit_neut4d.out`

**Comment by ramaniritika** [comment]
Hello,

No, phyloFit can't use multi-cpus at the same time. Depending on the size it could take a long time to run. 

Thanks!
Ritika

**Comment by Rusfell** [comment]
Got it.

Thansk!
