### ISSUE TITLE
warning: maf_read: MAF file must be sorted with respect to reference sequence if store_order=TRUE.  Ignoring out-of-order blocks

### ISSUE THREAD

**Issue by Rusfell** [CshlSiepelLab/phast#40]
Hi,
    When I tried to identify evolutionarily conserved elements using phastcons, I got this warning:

> warning: maf_read: MAF file must be sorted with respect to reference sequence if store_order=TRUE.  Ignoring out-of-order blocks

Does this have an impact on the results？ What shuold I deal with this warning?
Thanks!

**Comment by siepellab** [comment]
Hello,
Please make sure that the MAF is sorted by the coordinate of the reference genome. That should fix this warning.  
You can use maf_sort for your unordered MAF from the multiz/tba package from here - http://www.bx.psu.edu/miller_lab/dist/multiz-tba.012109.tar.gz

Ritika

**Comment by Rusfell** [comment]
Hi Ritika,

Thank you for your answer.

Rusfell
