### ISSUE TITLE
Calculation of phylogenetic models

### ISSUE THREAD

**Issue by lningyawen** [CshlSiepelLab/phast#41]
Hi

I  extracted the phylogenetic model from the MAF file by running PhyloFit: `phyloFit --tree '...' --subst-mod REV --out-root chr_10.maf`.  However, I found that I had 24 MAF files (one chromosome gets one MAF file, and I used the human genome as a reference) and one MAF file was quite large(> 15G), so obviously I could not merge them and do the calculations. If I calculate it separately, one MAF file is going to produce one .mod file, so I will have about 25 .mod files. So how do I go about merging these mod files. Or do you have any other suggestions? 
Any help will be much appreciated, Thanks.

Yawen

**Comment by siepellab** [comment]
Hello Yawen, 

You can use one mod file with all the species for the analysis of all the chromosomes.

Thanks!
Ritika

**Comment by lningyawen** [comment]
Hi Ritika,

Thank you for your answer. I have one more questions, are there any requirements for a tree to be used as a PhyloFit input? I am using orthofinder software to build the species trees and I found that some people are using whole genome alignment to build the trees. Do you have any advice for tree building?

Thanks again for your help!
Yawen

**Comment by siepellab** [comment]
Hi Yawen, 
You can use the whole genome alignment to build the tree too. 
We have used neighbor from the PHYLIP package to build trees in the past.

Hope this helps!
Ritika

**Comment by lningyawen** [comment]
Hi Ritika,

Thanks for all your help!

**Comment by lningyawen** [comment]
Hello Ritika,

I have been extracting mod files for ten days now and still no results. I thought the reason for the lack of results was that the input maf file was too large(15G), so I used a 1.3G maf file as input, but it has been running for four days and still no results. Is there something wrong with my input commands `phyloFit --tree '..species_tree..' --subst-mod REV --out-root chr_10.maf`, or am I setting the run time too low? Do you have any suggestions? 

Any help will be much appreciated, Thanks.

Yawen

**Comment by siepellab** [comment]
Hello, 
Your command is ok. Depending on the number of species as well as the length of the sequences phyloFit can take some time to run.

Thanks!
Ritika

**Comment by lningyawen** [comment]
Hello Ritika,

Sorry for getting back to you late. The alignment file contains approximately 60 species, which is probably why it takes a lot of time to do the calculations. 
Is it possible for me to extract the alignment file based on mitochondrial genome to calculate the mod files in this way? I think the mitochondrial genome is small enough to reduce the computing time.

Thanks!
Yawen

**Comment by siepellab** [comment]
Hey!
Sure you can use either mitochondrial genome which will only give you the maternal lineage or you can use a small segment of the whole genome which would probably give you a better estimate.
Ritika

**Comment by lningyawen** [comment]
Hello Ritika,

I obtained the .mod file by calculating the mitochondrial genome alignment file, which is very small, only 3M, and took less than an hour to calculate. I am also planning to extract a portion of the whole genome alignment for the calculation. Now I can move on to the next calculation using the mod file I have obtained.
Thank you very much for your help!

Yawen

**Comment by zuodabin** [comment]
> Hi Yawen, You can use the whole genome alignment to build the tree too. We have used neighbor from the PHYLIP package to build trees in the past.
> 
> Hope this helps! Ritika

Can I enter a tree of species created through orthofinder? When we run PhyloFit --EM, --precision HIGH, --subst, -mod REV

**Comment by zuodabin** [comment]
Can I enter a tree of species created through orthofinder? When we run PhyloFit --EM, --precision HIGH, --subst, -mod REV @siepellab
