### ISSUE TITLE
What does the "*" mean in the fasta format output from mas_split?

### ISSUE THREAD

**Issue by Rusfell** [CshlSiepelLab/phast#42]
Hi

I extracted the fasta format sequence from the MAF file by running mas_split: 

`msa_split Medicago_truncatula_ref_MtrunA17Chr0c17_Metru.maf --features ../04.cne_bedFiles/Medicago_truncatula_ref_MtrunA17Chr0c17_Metru_merged_cne.bed --by-category --out-format FASTA --out-root test`

In the output there are "-" and "*":

" > Medicago_truncatula
TTACCTGTTGATGGAGCAATCCCACCCAGAATGGTTGGCTGCTTCTCCCAAAGCATCCCTCTATTTTTGC
AAAATATTCATTGTACTTCCAAAACGCTGCTCATGCTTAACAAATGCCTCAATATTTCATCTCCTCTTTC
AAGATTGTCATCTATGTAAGTCTTGATATCTAACCTTCTTAGTGCACTATTGAGATGGCTTGTGAATGTT
TTACGAGTATCCTCGCCTCTGAAGCTAAGGAATACCTCATGTGTTTGTTTAGGATTTGTAGAGGAGGAGG
AGGAGGAAGCAAAATGATAA
\> Chamaecrista_fasciculata
\**********************************************************************
\**********************************************************************
\**********************************************************************
\**********************************************************************
\*******AAAA-----ATAG"

The "-" was supposed to be gaps in the alignment, but what does the "*" mean?

Any help will be much appreciated, Thanks.

Rusfell

**Comment by siepellab** [comment]
Hello,

The *s are missing data information, meaning there wasn't enough information in the MAF for that region of the alignment.

Hope that helps!
Ritika

**Comment by Rusfell** [comment]
> Hello,
> 
> The *s are missing data information, meaning there wasn't enough information in the MAF for that region of the alignment.
> 
> Hope that helps!
> Ritika

Got it!
Thanks for your reply...

Rusfell
