### ISSUE TITLE
error when compile 'dless' and 'pbsDecode'

### ISSUE THREAD

**Issue by Secretloong** [CshlSiepelLab/phast#43]
when I complied phast 1.5 & 1.6, I will run into the following reports:

```
make[1]: *** No rule to make target `bd_phylo_hmm.o', needed by `/phast-1.6/src/dless/../../bin/dless'.  Stop.
...
make[1]: *** No rule to make target `simplex_grid.o', needed by `/phast-1.6/src/prequel/../../bin/pbsDecode'.  Stop.
```

I found `phast_bd_phylo_hmm.c`, `phast_simplex_grid.c` and `phast_pbs_code.c` were conflicted with the Makefile. I should soft link them to  `bd_phylo_hmm.c`, `simplex_grid.c` and `pbs_code.c` separately. Then the installation could be finished. Are these files named by mistake?

**Comment by siepellab** [comment]
We had to rename these due to a conflict in the past. Will fix this error for the future releases
