### ISSUE TITLE
Please switch from pcre3 to pcre2

### ISSUE THREAD

**Issue by tillea** [CshlSiepelLab/phast#49]
Hi,
the Debian packaged version of phast received the famous [Bug #1000000](https://bugs.debian.org/1000000).  Despite I do not know pcre I tried hard to create a patch to close this bug as soon as possible.  So please take my code with some critical eyeballs.  I just made sure that that part of the test suite that was running flawlessly with pcre3 also works with the port to pcre2.  And yes, I know that you are using your own copy of pcre3 in your code base - but please read the opinion of other Debian developers who are concerned about security implications in the [full bug log](https://bugs.debian.org/1000000).
Thus I recommend to inspect and take over this [patch](https://salsa.debian.org/med-team/phast/-/blob/master/debian/patches/pcre2.patch).
BTW, it would be great if you could have a look at the test suite since only the part `make msa_view` is functional (*after fixing the Makefile - see Issue #47 ) the other parts are failing.  I'd love to test these with my patch but these are failing also with your pcre3 copy.
Kind regards, Andreas.

**Comment by heavywatal** [comment]
Hi, @tillea . Thank you for the maintaining Debian package. I have submitted several pull requests based on your suggestions. It would be nice those kind of fixes are merged into the upstream. But this patch #54 breaks something, and `make` fails on my environment, macOS 12.2. Maybe something too debian-specific are hardcoded?
