### ISSUE TITLE
filter out the FASTA format alignment by fewer than N sequence

### ISSUE THREAD

**Issue by yywyaoyaowu** [CshlSiepelLab/phast#51]
Hi, I have aligned 20 Species. But now I got the FASTA format(not the maf format). I want to get the aligbment that with at least 3 species aligned?  While msa_view -G parameter only have ALL, Any, or speciesfic speceis . Is there other parameter can help with this? Thanks very much!
Yao

**Comment by rhassett-cshl** [comment]
No, msa_view does not provide a parameter for that
