### ISSUE TITLE
maf_parse, Error got strand?

### ISSUE THREAD

**Issue by Elliott77** [CshlSiepelLab/phast#59]
Hi! I'm using maf_parse to chop up a large MAF file into smaller, more manageable files. 
I pass my MAF file to maf_parse and get an error:
ERROR: got strand ?

I don't notice anything out of the ordinary with the 'strand' field in my MAF. I've attached  a smaller MAF file with the first several blocks from my larger file—I can recreate the error with this. Would you have a look at the MAF file and let me know if anything there looks like it might trip up maf_parse? Thanks so much!

Here is the command I'm using:

maf_parse -o MAF -S 70000000 <maf file>

smaller MAF file:
[241mammalian_2020v2b.chr1_10_species_head.maf.txt](https://github.com/CshlSiepelLab/phast/files/10263156/241mammalian_2020v2b.chr1_10_species_head.maf.txt)

Thanks again!

Elliott

**Comment by rhassett-cshl** [comment]
If you search through the file, you will see there are '?' values in the strand column of the maf file. The *.maf file is expected to have either '+' or '-' for the strand column
