### ISSUE TITLE
Calculation of PIT values for multiple species

### ISSUE THREAD

**Issue by naturalstay** [CshlSiepelLab/phast#62]
Hi,
I want to identify CEs by 20-way multiple sequence alignment, but when I run consEntropy, I get an error that the number of species is too large to run. Can I determine the PIT value by pruning the number of species on the tree? Is this result reliable? Or do you have any good suggestion to tune the `expected-length` parameter
Looking forward to your reply.

**Comment by rhassett-cshl** [comment]
This tutorial contains detailed information on ways to tune the expected-length parameter: [http://compgen.cshl.edu/phast/phastCons-HOWTO.html#largedata](url)
