### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by songxh1996** [CshlSiepelLab/phast#64]
hello,I took the first chromosomes of the three bovine genomes and compared them, and it is worth noting that the chromosomes are not named differently. I got the .hal file with cactus and replaced it with a maf file, but when I used phastCons I got an error and I didn't know how to fix it. and I guess is doing something wrong.

[niu.tar.gz](https://github.com/CshlSiepelLab/phast/files/12093868/niu.tar.gz)

#
cactus jobStore chr1.dnd niu_align_chr1.hal --maxCores 16
#
cactus-hal2maf jobStore niu_align_chr1.hal \
niu_align_chr1.maf \
--chunkSize 1000000 \
--refGenome ARS-UCD_CHR1
###
phyloFit -i MAF niu_align_chr1.maf --tree chr1.dnd
###
phastCons niu_align_chr1.maf phyloFit.mod --target-coverage 0.25 --expected-length 12 --rho 0.4 --msa-format MAF > niu_align_chr1.wig

Reading tree model from phyloFit.mod...
Reading alignment from niu_align_chr1.maf...
Creating 'conserved' and 'nonconserved' states in HMM...
Computing emission probs (state 0, cat 0, mod 0)...
Computing emission probs (state 1, cat 1, mod 1)...
Computing posterior probabilities...
Segmentation fault (core dumped)

**Comment by chenzhao12** [comment]
i have same issue and you slove it?

**Comment by sgyproject** [comment]
I have the same problem, have you found any solution
