### ISSUE TITLE
Problems with estimating rho

### ISSUE THREAD

**Issue by kuangzhuoran** [CshlSiepelLab/phast#65]
my command line was: 
"msa_split  Chr1.maf  --in-format MAF  --windows 1000000,0 --out-root split --out-format SS --min-informative 1000 --between-blocks 5000"
"phastCons --estimate-rho $ss --no-post-probs $ss nonconserved.mod"

Then I met:
"
WARNING: likelihood decreased during EM: it 162851 total_logl=-298744.3233, prev_total_logl=-298744.1436
WARNING: likelihood decreased during EM: it 162853 total_logl=-298744.4031, prev_total_logl=-298744.1678
WARNING: likelihood decreased during EM: it 162855 total_logl=-298744.3233, prev_total_logl=-298744.1436
WARNING: likelihood decreased during EM: it 162857 total_logl=-298744.4031, prev_total_logl=-298744.1678
WARNING: likelihood decreased during EM: it 162859 total_logl=-298744.3233, prev_total_logl=-298744.1436
WARNING: likelihood decreased during EM: it 162861 total_logl=-298744.4031, prev_total_logl=-298744.1678
WARNING: likelihood decreased during EM: it 162863 total_logl=-298744.3233, prev_total_logl=-298744.1436
WARNING: likelihood decreased during EM: it 162865 total_logl=-298744.4031, prev_total_logl=-298744.1678
WARNING: likelihood decreased during EM: it 162867 total_logl=-298744.3233, prev_total_logl=-298744.1436
WARNING: likelihood decreased during EM: it 162869 total_logl=-298744.4031, prev_total_logl=-298744.1678
"

It seems to have been calculated something over 100,000 times. 
I've had a quick look and in those 100,000 calculations, 'total_logl=' and 'prev_total_logl=' are just 2-3 numbers repeating back and forth, without any other changes

The problem occurred on multiple chromosomes, and this is one of the files that had problems:
[Problematic.ss.file.txt](https://github.com/CshlSiepelLab/phast/files/13405841/Problematic.ss.file.txt)

**Comment by navyashukla-uom** [comment]
Hello, did you ever figure out what was happening?

**Comment by rhassett-cshl** [comment]
Refer to issue #44 with response to same question
