### ISSUE TITLE
too long segment of phastCon reslut

### ISSUE THREAD

**Issue by datou99** [CshlSiepelLab/phast#66]
Hello everyone,

I have run phastCon on the alignments of ~20 genomes, and for some chromosomes, I got very long conserved segments (longer than 100M) with the parameters "--most-conserved". For these too-long segments, the phastCon score in the 5th column is always like "-999999997". The situation is the same even when I add the parameter "--expected-length 20".

These too-long segments contribute to most parts of all the conserved segments (~70%). Do someone know why phastCont produced these >100Mbp segments, and how I can improve this?

Best,
Mia

**Comment by rhassett-cshl** [comment]
It could be due to missing or incomplete alignment data due to gaps. You can use msa_view to filter alignments to remove gapped regions and focus on well-aligned regions. If you run into any other issues, please include a sample of the data here or email to phasthelp@cshl.edu
