### ISSUE TITLE
calculate failed when use phyloP ACC

### ISSUE THREAD

**Issue by bighawkin** [CshlSiepelLab/phast#67]
the question is like that:
phyloP --method LRT --mode ACC --features all.bed phyloFit.mod  12species-Alignment.maf  > ACC-features.out
warning: maf_read: MAF file must be sorted with respect to reference sequence if store_order=TRUE.  Ignoring out-of-order blocks
ERROR ff_lrts: delta_lnl (-0.712266) <= -0.01

How to resolve this error? Looking forward to your reply.

**Comment by rhassett-cshl** [comment]
@bighawkin Did you sort the MAF file with respect to the reference sequence?
If you add the example files here or send to phasthelp@cshl.edu I can look into it further

**Comment by bighawkin** [comment]
Thank you for your reply. I use the phyloP CONACC mode to avoid errors. 
but I have a new question.
I would like to understand the gBGC results from phastBias. I used the command: phastBias fasta.maf ../4d/timetree-named_model.mod node --output-tracts out.gff. What is the relationship between the regions obtained and the ACC regions I calculated? Does overlap with ACC regions indicate that these are the regions under accelerated evolution driven by gBGC?
-------
results:
human	phastBias	gBGC_tract	123026	124009	872.659	.	.	.
human	phastBias	gBGC_tract	151608	151683	38.830	.	.	.
human	phastBias	gBGC_tract	159240	163343	3447.427	.	.	.
human	phastBias	gBGC_tract	190616	191037	361.086	.	.	.
human	phastBias	gBGC_tract	220893	221118	150.589	.	.	.
human	phastBias	gBGC_tract	225665	227476	1600.343	.	.	.
human	phastBias	gBGC_tract	240935	243132	1733.321	.	.	.
human	phastBias	gBGC_tract	243593	243710	86.909	.	.	.
human	phastBias	gBGC_tract	264714	265229	295.076	.	.	.
human	phastBias	gBGC_tract	298320	298832	404.554	.	.	.
----- 原始邮件 -----
发件人：rhassett-cshl ***@***.***>
收件人：CshlSiepelLab/phast ***@***.***>
抄送人：bighawkin ***@***.***>,  Mention ***@***.***>
主题：Re: [CshlSiepelLab/phast] calculate failed when use phyloP ACC (Issue #67)
日期：2024年11月28日 02点16分


@bighawkin Did you sort the MAF file with respect to the reference sequence?

If you add the example files here or send to ***@***.*** I can look into it further

**Comment by rhassett-cshl** [comment]
Yes, that is correct. It indicates that the regions under acceleration are being driven by gBGC. phastBias can be used for avoiding false positives in scans for positive selection. More information can be found in the paper here: https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1003684
