### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by mzytnicki** [CshlSiepelLab/phast#69]
Dear everyone,

I found a segfault in PhyloP.  I tried to make the example minimal, and I extracted the causing block.

[phyloP.tar.gz](https://github.com/user-attachments/files/16725961/phyloP.tar.gz)

The command is 

    phyloP --wig-scores phyloFit.mod hprc-v1.1-mc-grch38-full_fix_head.maf

Please note that not using `--wig-scores` does not crash PhyloP.

Any hint?

Thanks a lot.

**Comment by rhassett-cshl** [comment]
This issue should be resolved with the most recent commit. Please let me know if you are noticing any other issues.
