### ISSUE TITLE
Output  abnormal after phyloBoot

### ISSUE THREAD

**Issue by zskey-zn** [CshlSiepelLab/phast#71]
Hi, all

1. I use these 5 speices to identify HCEs, and use [gold fish method](https://www.science.org/doi/10.1126/sciadv.aav0547)  to get  muti-align file(Xenopus_tropicalis_mulitway.maf) .
![image](https://github.com/user-attachments/assets/8d05e4ba-ac9f-488e-8389-3ee3eed9b6ae)
2. then I use 4d-site to get 8,646 HCEs.
<code>
msa_view Xenopus_tropicalis_mulitway.maf --4d --features Xenopus_tropicalis.NC_030677.2.cds.gff > Xenopus_tropicalis.NC_030677.2.4d-codons.ss
......
msa_view Xenopus_tropicalis_mulitway.maf --4d --features Xenopus_tropicalis.NC_030686.2.cds.gff > Xenopus_tropicalis.NC_030686.2.4d-codons.ss
msa_view Xenopus_tropicalis.NC_030677.2.4d-codons.ss --in-format SS --out-format SS --tuple-size 1 > Xenopus_tropicalis.NC_030677.2.4d-sites.ss
......
msa_view Xenopus_tropicalis.NC_030686.2.4d-codons.ss --in-format SS --out-format SS --tuple-size 1 > Xenopus_tropicalis.NC_030686.2.4d-sites.ss
phyloFit --tree "(Callorhinchus_milii,(Xenopus_tropicalis,(Gallus_gallus,(Ornithorhynchus_anatinus,Homo_sapiens))))" --msa-format SS --out-root Xenopus_tropicalis.NC_030677.2.nonconserved-4d Xenopus_tropicalis.NC_030677.2.4d-sites.ss
......
phyloFit --tree "(Callorhinchus_milii,(Xenopus_tropicalis,(Gallus_gallus,(Ornithorhynchus_anatinus,Homo_sapiens))))" --msa-format SS --out-root Xenopus_tropicalis.NC_030686.2.nonconserved-4d Xenopus_tropicalis.NC_030686.2.4d-sites.ss
phastCons maf/NC_030677.2.maf Xenopus_tropicalis.NC_030677.2.nonconserved-4d.mod  --target-coverage 0.3 --expected-length 45 --msa-format MAF --seqname NC_030677.2 --most-conserved bed/NC_030677.2_most-cons.bed --score > wig/NC_030677.2.wig 
......
phastCons maf/NC_030686.2.maf Xenopus_tropicalis.NC_030686.2.nonconserved-4d.mod  --target-coverage 0.3 --expected-length 45 --msa-format MAF --seqname NC_030686.2 --most-conserved bed/NC_030686.2_most-cons.bed --score > wig/NC_030686.2.wig 
</code>
3. and I try to use phyloBoot to average mod ，then run phastCons again，Output is abnormal , bed file is empty with no bugs, can you give me some advise to fix it.
![image](https://github.com/user-attachments/assets/4290bd94-86be-40d3-8416-19b7822c3425)

**Comment by rhassett-cshl** [comment]
@zskey-zn Can you share the phyloBoot command you are using and some sample files so I can look into this further, thanks!
You can also send the files to phasthelp@cshl.edu

**Comment by zskey-zn** [comment]
sorry for later reply，multiple sequence alignment files and GFF files have been sent to the mailbox([phasthelp@cshl.edu](mailto:phasthelp@cshl.edu))

**Comment by zskey-zn** [comment]
multiple sequence alignment files and GFF files

**Comment by zskey-zn** [comment]
I resended with mailbox(zhengshang@frasergen.com)
