### ISSUE TITLE
Does the wig file generated by PhactCons also score the gaps and repeated sequences in the maf? Why do the coordinates of the bed file corresponding to the wig file not match？

### ISSUE THREAD

**Issue by helloworldABCD1234** [CshlSiepelLab/phast#74]
Does the wig file generated by PhactCons also score the gaps and repeated sequences in the maf? Why do the coordinates of the bed file corresponding to the wig file not match, for example, wig starts at 800 and bed starts at 1000,

**Comment by rhassett-cshl** [comment]
The wig file should have scores for each position in the alignment including gaps and repeated sequences. 
If you are referring to the --most-conserved option to generate the bed file, this will only include intervals of conserved elements. Those first 200 positions were likely not classified as conserved elements.

**Comment by helloworldABCD1234** [comment]
If you are referring to the --most-conserved option to generate the bed file, this will only include intervals of conserved elements. Those first 200 positions were likely not classified as conserved elements. what's that mean?

**Comment by helloworldABCD1234** [comment]
> The wig file should have scores for each position in the alignment including gaps and repeated sequences. If you are referring to the --most-conserved option to generate the bed file, this will only include intervals of conserved elements. Those first 200 positions were likely not classified as conserved elements.

If you are referring to the --most-conserved option to generate the bed file, this will only include intervals of conserved elements. Those first 200 positions were likely not classified as conserved elements.what's that mean?
