### ISSUE TITLE
When analyzing maf files with PhastCons, do we need to filter the species genomes of the comparison blocks in the maf file?

### ISSUE THREAD

**Issue by helloworldABCD1234** [CshlSiepelLab/phast#76]
When analyzing maf files with PhastCons, do we need to filter the species genomes of the comparison blocks in the maf file? For example, if the same species has multiple chromosome scaffolds, what impact will this have? Do we need to filter the maf file so that each species only has one chromosome?

s mouse.Chr.1              32232 23 +   295456 aaacaaataata------cattttatatt
s mouse.Chr.7              21142 23 + 59578282 aaacaaataata------cattttatatt
s rno.Chr.1             3294 22 +   302727 aaacaaataata------cattttatat-
s rno.Chr.7           1018910 28 + 39504823 aattaaataattTATAATaattttatat-
s hsa.Chr.1              119700 22 +   295604 aaacaaataata------aatttaatat-

The chromosome scaffold of mouse and rno here is duplicated. Do we need to remove one chromosome scaffold before conducting PhastCons analysis？

like this
s mouse.Chr.1              32232 23 +   295456 aaacaaataata------cattttatatt
s rno.Chr.1             3294 22 +   302727 aaacaaataata------cattttatat-
s hsa.Chr.1              119700 22 +   295604 aaacaaataata------aatttaatat-

**Comment by rhassett-cshl** [comment]
Yes. Chromosomes need to be analyzed separately with phast. One file per chromosome, ordered relative to the reference genome.

**Comment by helloworldABCD1234** [comment]
> each species only has one chromosome?

 Excuse me. Each species only has one chromosome in maf file right?

**Comment by rhassett-cshl** [comment]
@helloworldABCD1234 Yes

**Comment by bighawkin** [comment]
@helloworldABCD1234 @rhassett-cshl Excuse me, I want to known how to achieve "Each species only has one chromosome in maf", filter some  chromosome scaffold ？ or delete these block？ Are there any tools to help achieve this?
