### ISSUE TITLE
question about branch （phylop）

### ISSUE THREAD

**Issue by bighawkin** [CshlSiepelLab/phast#77]
I would like to know what the columns of results calculated by the branch program in phylop mean.
`phyloP --branch node --msa-format MAF --features file.bed  --method LRT --mode CONACC  ../4d/named_model.mod 12speciesalignment.maf  `
#chr	start	end	name	null_scale	alt_scale	alt_subscale	lnlratio	pval
 Do you have a detailed explanation of null_scale, alt_scale, alt_subscale, and lnlratio?

 Some papers use log10(alt_subscale) to represent the acceleration of this branch. Is this reasonable? Are there more detailed explanations or information available?

Thanks for your nice!

**Comment by rhassett-cshl** [comment]
@bighawkin 

There is more detailed information in the paper and supplement here:
[https://genome.cshlp.org/content/20/1/110](url)

The supplement provides more information about the estimated scale factors under the null and alternative model in section S2.1, the likelihood ratio test in section S2.2, phyloP's implementation in section S2.5, two-sided tests (all-branch or subtree) in section S3.3 and figure S1

If you want the log10 p-values, use the --wig-scores (-w) parameter to get these values in a *.wig file

null_scale is the estimated scaling factor under the neutral model for all branches, alt_scale is the estimated scaling factor under the alternative model for all branches, alt_subscale is the estimated scaling factor for the subtree under alternative model, lnlratio is the log likelihood ratio of alternative model to null model

Let me know if this needs any clarification or further explanation

**Comment by bighawkin** [comment]
I would like to ask whether alt_subscale can be used as a measure of evolutionary rate changes.
