### ISSUE TITLE
The coordinates of the bed file obtained by PhastCons are all conservative?

### ISSUE THREAD

**Issue by helloworldABCD1234** [CshlSiepelLab/phast#78]
The coordinates of the bed file obtained by PhastCons are all conservative?

**Comment by rhassett-cshl** [comment]
Yes, the bed file contains the coordinates that PhastCons identifies as conserved. The --target-coverage and --expected-length parameters can be tuned to set the threshold for identifying an element as conserved. Refer to this documentation for more detailed information on using these tuning parameters: [http://compgen.cshl.edu/phast/phastCons-HOWTO.html](url)
