### ISSUE TITLE
lol_find_lol() always return NULL;

### ISSUE THREAD

**Issue by amin-saffari** [CshlSiepelLab/phast#9]
This is because lol_find_list() is recursively called to look at LIST_LIST type and not each level's type! 
I submitted a pull request (#8) concerning this.

**Comment by ramaniritika** [comment]
What bug/error message does this fix?

**Comment by mjhubisz** [comment]
lol_find_list() is a function to recursively search a listOfList object for an element with a given name and type, so I do not think the type should be changed when the function calls itself, and the code is correct as is. However I am curious what you are trying to fix; possibly the function is mis-used somewhere? If you have a reproducible example of a bug we'd be happy to take a look.

**Comment by amin-saffari** [comment]
@mjhubisz Well, the chance of mis-using is not really low! 

Concerning the reproducible example, I can't think of any particular dataset:
Any data which passed through function [run_phyloFit(pf)](https://github.com/CshlSiepelLab/phast/blob/master/src/phyloFit/phyloFit.c#L356) can be used in this case!

[lol_push_treeModel()](https://github.com/CshlSiepelLab/phast/blob/master/src/lib/base/list_of_lists.c#L177) push all the results in a variable with type ListOfList (e.g `pf->results`). To retrieve the pushed tree (or anyother information) I am using ` lol_find_list ` like `List *currResult = lol_find_list(pf->results,"tree",LIST_LIST);`

This should report me the tree, right!? However, the result is always NULL!
I should mention that my example is based on `lstName == "tree"` but the similar situation holds for other element-name as well (e.g alphabet, backgd, likelihood,... ).

I hope this explanation make my issue more clear, and thanks in advance for any clarification!

**Comment by mjhubisz** [comment]
Almost everything in the code dealing with listOfLists is written to facilitate the interface between the C code and R for purposes of the RPHAST package. (In fact, the ListOfList structure is designed to directly mirror R's concept of a list). If you are running phyloFit on the command-line, the model is written to a file, so you should not need to have to retrieve it from the listOfLists structure.

That being said, run_phyloFit pushes the model to the list using the lol_push_treeModel() function. To retrieve the model from pf->results, you would have to use lol_find_list(pf->results, "tm", LIST_LIST). Or, you could get other elements such as "likelihood", "rate.matrix", "backgd", etc... anything that's pushed to the list in the lol_push_treeModel function (though you'd need to specify the appropriate type for each).

**Comment by amin-saffari** [comment]
I am using PHAST(mostly phyloFit) as a library linked to my program, and It's not really a cheap process to write all results to a file and then read them back into the memory.That's why I am using ListOfLists! 

However, I think I find the correct use of lol_find_list() to retrieve my element of interest:
`ListOfLists *currLOL = lol_find_lol(pf->results,"tmp.mod");`
`List *currResult = lol_find_list(currLOL,"tree",CHAR_LIST);`

Given this solution, I don't think my pull request makes that much of sense!

Thanks for your time and help!
